### ISSUE TITLE
How do I set the data for the x-axis?

### ISSUE THREAD

**Issue by 978740431** [infinum/flutter-charts#13]
Now the display is 0~N, I want to display the date, how do I need to set

**Comment by lukaknezic** [comment]
Hey,

With GridDecoration or VerticalAxisDecoration you have `valueFromIndex`. This is a function that will return you index and you can return any string you want as label text.

Hope that helps 😄

**Comment by 978740431** [comment]
Thank you very much, it is ready to use.
I hope there is a case in the demo, because my English and flutter technology is very poor, so after reading your reply I still took some time to solve it, if the case has examples, it will be very good to help sdk users

**Comment by lukaknezic** [comment]
Great 🎉 
Okay, thanks for input. I'll add that to readme and maybe some examples 😃
