### ISSUE TITLE
Is it possible to have two lines with different horizontal axis values?

### ISSUE THREAD

**Issue by roly151** [infinum/flutter-charts#34]
I would like to create a line chart with two lines. But the horizontal axis values for each line need to be different. One is a temperature (so could be 0 to 40 degrees), the other one is a chance of rain (so could be 0% to 100%). Is this possible? 

Hopefully the question makes sense.

**Comment by lukaknezic** [comment]
Hey @roly151 

If I understand correctly I think easiest way to do this is just to build 2 charts and add them in a Stack.
Currently library is not supporting different X or Y coordinates for different data on same chart.

**Comment by roly151** [comment]
Thanks - I did consider that. I'll give it a go.
