### ISSUE TITLE
Incorrect Offset calculation in TargetLineDecoration

### ISSUE THREAD

**Issue by vsilux** [infinum/flutter-charts#35]
When we setting `ChartData. axisMin` the Offset in `TargetLineDecoration.applyPaintTransform` calculates wrongly. 

The problem is in:
`Offset(state.defaultPadding.left + state.defaultMargin.left,
      _height - (state.defaultMargin.bottom + state.defaultPadding.bottom) - (scale * (target ?? 0.0) + _minValue);`

instead of adding `_minValue` we should subtract it from `scale * (target ?? 0.0)`

**Comment by itsJoKr** [comment]
TargetLineDecoration is deprecated in 3.0 so closing this.
