### ISSUE TITLE
x Axis customisation for selected index like background color, corner radius

### ISSUE THREAD

**Issue by nikunjramialtais** [infinum/flutter-charts#39]
I got click event of xAxis label but I want to increase the clickable area of the x-axis label and want to show selected xAxis with the rounded background colour.
Check x Axis with value 15. I want to show like this and increase click area, currently its working text click which is not responsive 
<img width="466" alt="Screenshot 2022-03-02 at 2 17 38 PM" src="https://user-images.githubusercontent.com/97666701/156373715-ca4c6ab5-76cb-41d4-a2cb-bd3680edb70d.png">

**Comment by lukaknezic** [comment]
Hey @nikunjramialtais, you can do background color with `SelectedItemDecoration`. For clicking are you using `onItemClicked` from `ChartBehaviour` or are you using something else? 

As for rounded background color on xAxis, this is not available by default, that can be done either by making new decoration or expanding the existing VerticalDecoration/HorizontalDecoration. 

I will try to replace actual text on Horizontal and Vertical decorations to be widgets (Text or any other) so this will be much easier to implement then.

**Comment by itsJoKr** [comment]
We're redone the click handling, so should be better now. Plus, there's WidgetDecoration and you can show any kind of widget.
