### ISSUE TITLE
Show labels on stacked Bar Chart in sections

### ISSUE THREAD

**Issue by ABausG** [infinum/flutter-charts#42]
Hello,

I want to show the values of a section in a stacked bar chart inside the section. Is there a way to do that? By using `ValueDecoration` I was only able to produce a label for the whole bar.

**Comment by lukaknezic** [comment]
Hey @ABausG 

You might want to check out `SelectedItemDecoration`. It is meant for selected item and clicking but it can also be used as sections and have multiple of them with different `selectedItem` id.

**Comment by ABausG** [comment]
I was able to get it working with the `ValueDecoration` and the `valueArrayIndex`
However I noticed that as the alignment is based on the max value the label is not the desired one if it should be the amount of the respective section.
I have added a function to generate a label based on the item in addition to the value. I will open a PR soon
