### ISSUE TITLE
ValueDecoration Alignment not working with maxBarWidth

### ISSUE THREAD

**Issue by ABausG** [infinum/flutter-charts#43]
<img width="743" alt="Screenshot 2022-03-23 at 09 04 05" src="https://user-images.githubusercontent.com/7288963/159651716-4e4d2bd2-da0e-4ca5-9fd6-86bb1249e47f.png">

When setting `maxBarWidth` in the item options the ValueDecoration alignment is not properly aligned anymore.

```
...
                foregroundDecorations: [
                  ValueDecoration(
                    textStyle: Theme.of(context).textTheme.bodyText2,
                    alignment: Alignment.topCenter,
                  ),
                ],
                itemOptions: BarItemOptions(
                  maxBarWidth: 100,
...
```

**Comment by itsJoKr** [comment]
ValueDecoration is deprecated in 3.0. This could be recreated with WidgetDecoration and little bit of math.
