### ISSUE TITLE
APK will be increased by 28 MB when adding this package

### ISSUE THREAD

**Issue by nilsreichardt** [infinum/flutter-charts#48]
## Description
When adding this package, will this increase the size of the APK by 28 MB.

APK with this package: 45.5 MB
APK without the asset folder: 17 MB

Is the `asset` folder with all the GIFs really needed? I assume the GIFs and images in the `asset` are only for the `README.md`, right?

**Comment by lukaknezic** [comment]
Yeah assets are used only in README.

**Comment by lukaknezic** [comment]
Available in 2.0.0+2
