### ISSUE TITLE
Is there MaxVisibleRange option available in scrollable chart ?

### ISSUE THREAD

**Issue by irshadshan000** [infinum/flutter-charts#58]
Hi
I would like to ask a doubt related scrollable chart, is there available maxVisibleRange property in scrollable (Like if we have a view port, can we set a range it should be show in that range in any size of device also. I have checked with ipad and android mobile, there is candle items showing in graph view different numbers, in the sense in iPad there is more than 10 items showing in a view in scrollable chart, but in android pixel phone its showing only 7 items in a view(Actually I made a graph for Week view). so If have maxVisibleRange property it will help for my logic for loading more data, Its my question / doubt, can you please reply?
Thank you..

**Comment by lukaknezic** [comment]
Hey @irshadshan000,

At the moment lib cannot do that, but that is a great suggestion and I think it could be really useful.

For now you can try and get the available screen width and using that as `maxBarWidth` so something like:
```dart
LayoutBuilder(
  builder: (context, constraints){
    final _itemSize = constraints.maxWidth / _numbersOfItemsYouWantToShow;
    ...
    // Use _itemSize in `ChartState(..., options: BarItemOptions(maxBarWidth: _itemSize))`
```

**Comment by irshadshan000** [comment]
Yeah, Really Thank you lukaknezic for the reply, Almost we have archived this element day before yesterday only.
but I am getting more clarity from your suggestion.
I am sharing those things, I got archived this maxvisible range and by scrolling time scroll min & scroll max values also.
  
  maxBarWidth:_isScrollable ? (MediaQuery.of(context).size.width)/(offset!*2.0) : 4.0 
  
`  //**scroll min & scroll max I have archived in another way,**
  
  
   void _onUpdateScroll(ScrollMetrics metrics) {
    print("Scroll Update");

    print("max");
    print(((metrics.extentBefore / offset!) / offset!) + offset!);
    print("min");
    print(((metrics.extentBefore / offset!) / offset!));
    setState(() {
      maxvalue=(((metrics.extentBefore / offset!) / offset!) + offset!).toInt();
      minvalue=((metrics.extentBefore / offset!) / offset!).toInt();
    });
}

  child: NotificationListener<ScrollNotification>(
                  onNotification: (scrollNotification) {
                    if (scrollNotification is ScrollStartNotification) {
                      _onStartScroll(scrollNotification.metrics);
                    } else if (scrollNotification is ScrollUpdateNotification) {
                      _onUpdateScroll(scrollNotification.metrics);
                    } else if (scrollNotification is ScrollEndNotification) {
                      _onEndScroll(scrollNotification.metrics);
                    }

                    return true;

                  },
                  child: SingleChildScrollView(`
https://user-images.githubusercontent.com/88364868/163108041-9e1a2206-0f9a-40bc-a0c2-e43d33c17797.mp4
