### ISSUE TITLE
Scrollable chart demo not working

### ISSUE THREAD

**Issue by IsaiChristian** [infinum/flutter-charts#65]
Hi I downloaded the package and Im playing around with your demo, but scrollable is not working correctly, Maybe Im not sure how it suppose to work? I try to drag and click and I looked for any type of scroll bar with no success I attach video of the issue, this is on WINDOWS.

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (3 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

https://user-images.githubusercontent.com/2268156/193211436-7265d1b6-27cd-42f7-b93d-89130189eae9.mp4

Error happen if I build for windows, either in debug or if I build it.

**Comment by IsaiChristian** [comment]
Is there any news on this bug?

**Comment by itsJoKr** [comment]
@IsaiChristian it took me some time to setup this on Windows. Basically, the horizontal scroll on Windows seems in general to be disabled. For example this doesn't work:

This doesn't scroll for me
```dart
    return Scaffold(
      body: Scrollbar(
        trackVisibility: true,
        child: SingleChildScrollView(
            physics: ScrollPhysics(),
            controller: _controller,
            scrollDirection: Axis.horizontal,
            child:
            Row(children: [
              Container(width: 400, height: 300, color: Colors.red),
              Container(width: 400, height: 300, color: Colors.black),
              Container(width: 400, height: 300, color: Colors.red),
              Container(width: 400, height: 300, color: Colors.blue),
            ],)
        ),
      ),
    );
```
So this issue is not due to charts library. I tested and found that there is a way to enable it here:
https://stackoverflow.com/a/69202112

If you do that then it will work.

**Comment by IsaiChristian** [comment]
Thanks for the solution I'll check on it.
