### ISSUE TITLE
Take Swift Charts as inspiration

### ISSUE THREAD

**Issue by pablojimpas** [infinum/flutter-charts#70]
Apple introduced Swift Charts in WWDC22, a SwiftUI library to represent complex datasets using charts. It has a lot of similarities with this package, both in terms of functionality and looks.

The level of thought and detail put into Swift Charts is amazing, the API is clean, easy to use and orthogonal to help combine features quickly. The graphic aspect is also great, it has reasonable defaults, the right amount of customizability and renders beautifully almost always.

Now that this package is being further developed and with the upcoming breaking changes in the next major version (v3), I think it's a good opportunity to maybe “steal” some ideas from Swift Charts. If you don't find this proposal appealing for the next version of `flutter-charts`, at least it's good to know the state of the art and other “competing” implementations in the charting world.

Thanks for your work!

Further reference:
- https://developer.apple.com/documentation/charts
- [Creating a chart using Swift Charts](https://developer.apple.com/documentation/charts/creating-a-chart-using-swift-charts)
- [Hello Swift Charts](https://developer.apple.com/videos/play/wwdc2022/10136/)
- [Swift Charts: Raise the bar ](https://developer.apple.com/videos/play/wwdc2022/10137/)

**Comment by itsJoKr** [comment]
Hey, thanks for the idea @pablojimpas 

We have already looked at what Apple is doing. I would say their focus is more on the fast-creation of simple charts. They can all be implemented in charts_painter but it would take more code.

On the other hand, charts_painter 3.0 is promoting customizability, and the ability to add any widget for an item or decoration. While on Apple's side, they give you predefined "marks" and don't display prominently how to incorporate a custom view into the chart.

So the biggest difference is a different way of thinking between these two charting solutions. Besides that, there are possible improvements. For example, they have well supported accessibility, while so far that hasn't been focus in charts_painter.

**Comment by pablojimpas** [comment]
Thanks for your comments! I understand that this library aims to be way more flexible, and I like it that way. As long as there is a straightforward API to achieve the easy stuff, I'm fine with adding as much customizability as possible on top.

I just wanted to let these resources here as something to have in mind when designing and making decisions for future changes in `charts_painter`. Accessibility is in fact one of the biggest selling points of Apple UI solutions, it's a reference to follow for the future.

**Comment by itsJoKr** [comment]
Closing this as it's not an running issue.
