### ISSUE TITLE
too much padding in vertical legend and x-axis of bar chart.  is there any way to reduce this?

### ISSUE THREAD

**Issue by singhjaskirat984** [infinum/flutter-charts#80]
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-17 at 10 19 01](https://user-images.githubusercontent.com/44332209/212817370-f3029b2a-b0d0-467d-8442-6f7a48029879.png)

**Comment by Zeeshan0201** [comment]
facing same issue
