### ISSUE TITLE
Not a bug, just failing to understand

### ISSUE THREAD

**Issue by kobi666** [infinum/flutter-charts#82]
Hi,
I really like the solution and it's simplicity.
that being said, I can't seem to understand from the documentation how to achieve the things you display in your gorgeous demo.
mainly I am interested in two things:
1. control over vertical and horizontal descriptions.
E.G a chart of some values divided by days and underneath a Sun,Mon,Tue etc
2. how do you produce the popups with little values upon pressing a bar?

**Comment by itsJoKr** [comment]
I'm not sure which chart specifically you're looking for, if you share a screenshot I can give you. Also, all charts from the demo are inside `charts_web` (playground) or `example` (examples) folder.

1. Use Horizontal or Vertical decorations. Then specify value for index:
```
                VerticalAxisDecoration(
                  valueFromIndex: (value) {
                    if (value == 0) {
                      return 'Mon';
                    } else if (value == 1) {
                      return 'Tue';
                    }
                    ...
                  }
                ),
```

2.

You can put generic item click listener

```
              Chart(
                state: ChartState<void>(
                  behaviour: ChartBehaviour(
                    onItemClicked: () {

                    }
                  ),
                  data: ...
                  itemOptions: BarItemOptions(...)
```

Or go custom with your widgets:

```
              Chart(
                state: ChartState<void>(
                  data: ...
                  itemOptions: WidgetItemOptions(
                     widgetItemBuilder: (data) {
                           // here return your widget. It can be stateless, it can be inkwell, it can show toggle...
                           return InkWell(child: YourWidget....))
                     }
)
```

**Comment by itsJoKr** [comment]
Hopefully I clarified your problem. So I'm going to close this issue. If you have any other questions, you can reopen.
