### ISSUE TITLE
Issue with horizontal axis values

### ISSUE THREAD

**Issue by ByteSizedMarius** [infinum/flutter-charts#85]
Hi, I would basically like a scrollable chart like the one seen in the example gif:

![](https://raw.githubusercontent.com/infinum/flutter-charts/master/assets/scrollable_chart.gif)

However, I'm struggling with the values on the horizontal axis. They seem to disappear, as soon as the chart is scrollable (width > screen width). This is also the case for the scrollable chart in the examples:

![1](https://user-images.githubusercontent.com/20816169/218891325-66c5d9eb-ec08-44cf-9940-4da29751f244.png)
![2](https://user-images.githubusercontent.com/20816169/218891330-645f9587-da40-4906-a02d-c9899832a397.png)

Am I missing something here?

Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (9 months ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

Thanks!

**Comment by itsJoKr** [comment]
Should be fixed in 3.1.0
