### ISSUE TITLE
Candle Charts

### ISSUE THREAD

**Issue by athompson887** [infinum/flutter-charts#88]
I am trying to create a candle chart with a specific range - for example 0 - 15.  I cannot find an option to do this.   Currently if I only have a value from 0 - 2 - then the highest value shown is 2.  Is this functionality possible?

**Comment by itsJoKr** [comment]
Hi @athompson887 

There's no specific range method, but you could do this way.

In ChartData there is `valueAxisOverMax` which specifies `How much should chart draw above max value in the chart`.

```dart
ChartData(..., valueAxisOverMax: (15 - _calculateYourHighestValueSomehow)).
```

**Comment by athompson887** [comment]
Thank you very much - that is really helpfull
