### ISSUE TITLE
Bar width is Bigger when we have few values

### ISSUE THREAD

**Issue by mobinshaik999** [infinum/flutter-charts#92]
Hai thanks for the beautiful plugin, 

I was using this plugin to show Bp Values  over time, 

when the data is less then my bar width is bigger , tried to fix this using provided keys 
maxBarWidth, minBarWidth but still it doesn't helped me .

<img width="322" alt="Screenshot 2023-08-20 at 1 18 51 AM" src="https://github.com/infinum/flutter-charts/assets/58165072/ad8a72a8-29e8-4dfd-932e-13ad5c5bd917">

How can I have default bar width ? is any option for it . Please help out me here 
Thanks in Advance.

**Comment by lukaknezic** [comment]
Hey @mobinshaik999 

If I understand correctly you want the chart to not take whole width if it doesent have that much data. 
Chart will always try to fill in the space you put it in. Other way to get over this is to set:
```dart
behaviour: ChartBehaviour(
  scrollSettings: ScrollSettings(),
),
```
To your `ChartState` this will prioritize the values for min and max you set

**Comment by lukaknezic** [comment]
I'm closing this since there is no follow up. Feel free to reopen if neccessary
