### ISSUE TITLE
how to change to horizontal position?

### ISSUE THREAD

**Issue by andre-ab** [infinum/flutter-charts#98]
how to change to horizontal position?

![image](https://github.com/infinum/flutter-charts/assets/10952239/8270d8fa-0a10-4e5e-af14-a3250a445ebd)

**Comment by andre-ab** [comment]
add  RotatedBox in Widge Chart

```
  RotatedBox(
      quarterTurns: 1,
      child: Chart(...),
      )

```
add rotated box in widget chart,
The problem was only with the numbers "0,1.."

![image](https://github.com/infinum/flutter-charts/assets/10952239/ef2f645a-de29-4df6-b59a-a0a16bf8ffea)

**Comment by lukaknezic** [comment]
Hey @andre-ab. There is no easy way to do this yet. You would have to make your own decoration with rotated values. You can do that with WidgetDecoration as well. ex:
```dart
WidgetDecoration(
  widgetDecorationBuilder: (builder, state, itemWidth, verticalMultiplier) {
    return Stack(
      children: [
        ...List.generate(
          state.data.listSize,
          (index) => Positioned(
            bottom: 0,
            width: itemWidth,
            height: 32,
            left: index * itemWidth,
            child: Center(
              child: RotatedBox(
                quarterTurns: 3,
                child: Text('$index'),
              ),
            ),
          ),
        ),
      ],
    );
  },
  margin: EdgeInsets.only(bottom: 32),
)
```
